# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Miroslav Mirkov
tagline:          'Never send a humant to do a michne\'s work'
description:      ''
url:              http://mmirkov.github.io
baseurl:          /

author:
  name:           'Miroslav Mirkov'
  url:            https://mirkov.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
