# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Miroslav Mirkov
tagline:          'Just some random thoughts'
description:      ''
url:              https://mmirkov.github.io
baseurl:          /

author:
  name:           'Miroslav Mirkov'
  url:            https://mmirkov.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
